<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AdPerformance.Core\AdPerformance.Core.csproj" />
    <ProjectReference Include="..\AdPerformance.Infrastructure\AdPerformance.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.7" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AdPerformance</AssemblyName>
    <RootNamespace>AdPerformance.CLI</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PublishSingleFile)' == 'true'">
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

</Project>
